-- PRD v3.0: perfis, blocos, leads (NoCode Folio)

CREATE TABLE public.perfis (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id uuid NOT NULL UNIQUE REFERENCES auth.users (id) ON DELETE CASCADE,
  slug text NOT NULL UNIQUE,
  nome_completo text,
  bio text,
  avatar_url text,
  configuracao_tema jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.blocos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  perfil_id bigint NOT NULL REFERENCES public.perfis (id) ON DELETE CASCADE,
  tipo text NOT NULL CHECK (tipo IN ('link', 'imagem', 'texto', 'mapa', 'video', 'newsletter')),
  titulo text,
  conteudo jsonb NOT NULL DEFAULT '{}'::jsonb,
  colunas smallint NOT NULL DEFAULT 1 CHECK (colunas >= 1 AND colunas <= 4),
  linhas smallint NOT NULL DEFAULT 1 CHECK (linhas >= 1 AND linhas <= 2),
  ordem smallint NOT NULL DEFAULT 0,
  visivel boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.leads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  perfil_id bigint NOT NULL REFERENCES public.perfis (id) ON DELETE CASCADE,
  email text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX blocos_perfil_ordem_idx ON public.blocos (perfil_id, ordem);
CREATE INDEX leads_perfil_idx ON public.leads (perfil_id);

ALTER TABLE public.perfis ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

CREATE POLICY "perfis_select_publico"
  ON public.perfis FOR SELECT
  USING (true);

CREATE POLICY "perfis_insert_proprio"
  ON public.perfis FOR INSERT
  WITH CHECK (auth.uid() = usuario_id);

CREATE POLICY "perfis_update_proprio"
  ON public.perfis FOR UPDATE
  USING (auth.uid() = usuario_id);

CREATE POLICY "blocos_select_publico"
  ON public.blocos FOR SELECT
  USING (true);

CREATE POLICY "blocos_insert_dono"
  ON public.blocos FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.perfis
      WHERE perfis.id = blocos.perfil_id
        AND perfis.usuario_id = auth.uid()
    )
  );

CREATE POLICY "blocos_update_dono"
  ON public.blocos FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.perfis
      WHERE perfis.id = blocos.perfil_id
        AND perfis.usuario_id = auth.uid()
    )
  );

CREATE POLICY "blocos_delete_dono"
  ON public.blocos FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.perfis
      WHERE perfis.id = blocos.perfil_id
        AND perfis.usuario_id = auth.uid()
    )
  );

CREATE POLICY "leads_insert_publico"
  ON public.leads FOR INSERT
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.perfis WHERE perfis.id = leads.perfil_id)
  );

CREATE POLICY "leads_select_dono"
  ON public.leads FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.perfis
      WHERE perfis.id = leads.perfil_id
        AND perfis.usuario_id = auth.uid()
    )
  );

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  base_slug text;
  final_slug text;
  counter int := 0;
BEGIN
  base_slug := COALESCE(
    NULLIF(regexp_replace(lower(split_part(NEW.email, '@', 1)), '[^a-z0-9_]', '', 'g'), ''),
    'user'
  );
  final_slug := base_slug;
  WHILE EXISTS (SELECT 1 FROM public.perfis WHERE slug = final_slug) LOOP
    counter := counter + 1;
    final_slug := base_slug || counter::text;
  END LOOP;

  INSERT INTO public.perfis (usuario_id, slug, nome_completo)
  VALUES (
    NEW.id,
    final_slug,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', '')
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'avatars',
  'avatars',
  true,
  5242880,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "avatars_select_publico"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'avatars');

CREATE POLICY "avatars_insert_dono"
  ON storage.objects FOR INSERT
  WITH CHECK (
    bucket_id = 'avatars'
    AND auth.uid()::text = (storage.foldername(name))[1]
  );

CREATE POLICY "avatars_update_dono"
  ON storage.objects FOR UPDATE
  USING (
    bucket_id = 'avatars'
    AND auth.uid()::text = (storage.foldername(name))[1]
  );

CREATE POLICY "avatars_delete_dono"
  ON storage.objects FOR DELETE
  USING (
    bucket_id = 'avatars'
    AND auth.uid()::text = (storage.foldername(name))[1]
  );
